# Generated by Django 4.1.1 on 2022-09-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_food_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='priority_category',
        ),
        migrations.AlterField(
            model_name='dish',
            name='active',
            field=models.BooleanField(db_index=True, default=True, null=True, verbose_name='Показывать блюдо'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Рецепт приготовления'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='dislikes',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='dislike_guests', to='tg_food_bot.dish', verbose_name='Не любимые рецепты'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='likes',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='like_guests', to='tg_food_bot.dish', verbose_name='Любимые рецепты'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Телеграм ID'),
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='tg_food_bot.category', verbose_name='Любимая категория блюд'),
        ),
        migrations.AddField(
            model_name='guest',
            name='priority_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='tg_food_bot.category', verbose_name='Любимые категория блюд'),
        ),
    ]
