# Generated by Django 4.1.1 on 2022-09-21 14:15

from django.db import migrations


def add_categories(apps, schema_editor):
    Category = apps.get_model('tg_food_bot', 'Category')
    categories = [
        'Вегетарианские блюда',
        'Рыбные блюда',
        'Салаты',
        'Блюда без глютена',
    ]
    for category_title in categories:
        category, created = Category.objects.get_or_create(
            title=category_title,
        )
        category.save()


def rollback(apps, schema_editor):
    Category = apps.get_model('tg_food_bot', 'Category')
    for category in Category.objects.all():
        category.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tg_food_bot', '0002_category_remove_dish_category_and_more'),
    ]

    operations = [
        migrations.RunPython(add_categories, rollback),
    ]
