# Generated by Django 4.1.1 on 2022-09-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_food_bot', '0005_dish_price_dish_price_currency_guest_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='telegram_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Телеграм ID'),
            preserve_default=False,
        ),
    ]
