# Generated by Django 4.1.1 on 2022-09-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_food_bot', '0006_alter_guest_name_alter_guest_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price_portion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена порции'),
        ),
    ]
