# Generated by Django 4.1.1 on 2022-09-27 13:48

from django.db import migrations
from django.db.models import F

def update_dish(apps, schema_editor):
    Dish = apps.get_model('tg_food_bot', 'Dish')
    Dish.objects.update(
        price_portion=F('price'),
    )

def rollback(apps, schema_editor):
    Dish = apps.get_model('tg_food_bot', 'Dish')
    Dish.objects.update(
        price_portion=None,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tg_food_bot', '0007_dish_price_portion'),
    ]

    operations = [
        migrations.RunPython(update_dish, rollback),
    ]
