# Generated by Django 4.1.1 on 2022-09-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_food_bot', '0009_remove_dish_price_remove_dish_price_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='price_portion',
            new_name='price',
        ),
    ]
